# Generated by Django 6.0.5 on 2026-05-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='disponiblidadMueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estadoMueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoCuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoEnvio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('correo', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=9)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
                ('tipoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipocuenta')),
            ],
        ),
        migrations.CreateModel(
            name='mueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('precio', models.IntegerField()),
                ('disponiblidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disponiblidadmueble')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadomueble')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuenta')),
                ('idMueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mueble')),
                ('idTipoEnvio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoenvio')),
            ],
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('idEnvio', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuenta')),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
                ('idMueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mueble')),
                ('idTipoEnvio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoenvio')),
            ],
        ),
    ]
