# Generated by Django 6.0.5 on 2026-05-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='usuario_cuenta',
            field=models.CharField(default='', max_length=70),
        ),
    ]
