# Generated by Django 6.0.5 on 2026-05-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cuenta_usuario_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipoCuenta',
        ),
    ]
