# Generated by Django 6.0.5 on 2026-05-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cuenta_tipocuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
