# Generated by Django 6.0.5 on 2026-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_nombre_cuenta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
