# Generated by Django 6.0.5 on 2026-05-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_compra_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='cantidad',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='idMueble',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio',
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='detalleCompra',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.IntegerField(default=0)),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.compra')),
                ('idMueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mueble')),
            ],
            options={
                'unique_together': {('idCompra', 'idMueble')},
            },
        ),
    ]
