# Generated by Django 6.0.5 on 2026-05-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_cantidad_compra_total_remove_compra_idmueble_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='idTipoEnvio',
        ),
        migrations.AddField(
            model_name='compra',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
