# Generated by Django 6.0.5 on 2026-05-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_compra_idtipoenvio_compra_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='usuario_cuenta',
            field=models.IntegerField(default=0),
        ),
    ]
