# Generated by Django 6.0.5 on 2026-05-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cuenta_usuario_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
