# Generated by Django 6.0.5 on 2026-05-22 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mueble_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaMueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mueble',
            name='categoria_mueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoriamueble'),
        ),
    ]
