# Generated by Django 6.0.5 on 2026-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_categoriamueble_mueble_categoria_mueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='telefono',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
