# Generated by Django 6.0.5 on 2026-05-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cuenta_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
