# Generated by Django 6.0.5 on 2026-05-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cuenta_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoProductoComprado',
            fields=[
                ('idestadocompra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
    ]
