# Generated by Django 6.0.5 on 2026-05-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_estadoproductocomprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='idEsProdCom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estadoproductocomprado'),
        ),
    ]
